swagger: "2.0"
info:
  description: "Aplicação de consulta star wars"
  version: "1.0.0"
  title: "star wars"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /pessoas/listaOrdenada:
    get:
      tags:
      - "pessoas"
      summary: "Busca todos os personagens ordenado"
      description: "Busca todos os personagens e ordena por quantidade de filmes e nome (ordem alfabética)"
      produces:
      - "application/json"
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            type: array
            items: 
              $ref: "#/definitions/PeopleBasic"
        400:
          description: "Parâmetro inválido"
          schema:
            $ref: "#/definitions/Fault"
        404:
          description: "Serviço não disponível"
          schema:
            $ref: "#/definitions/Fault"

definitions: 
  PeopleBasic: 
    type: object
    description: A person within the Star Wars universe
    required:
    - name
    - mass
    - birth_year
    - films
    properties:
      name:
        description: The name of this person.
        type: string
      mass:
        description: The mass of this person in kilograms.
        type: string
      birth_year:
        description: The birth year of this person. BBY (Before the Battle of Yavin) or
          ABY (After the Battle of Yavin).
        type: string
      films:
        description: An array of urls of film resources that this person has been in.
        type: array
        items:
          type: string


  Fault:
    type: object
    properties:
      mensagens:
        type: array
        items:
          $ref: "#/definitions/Message"
      dataOcorrencia:
        type: string
        format: date-time
      fonte:
        type: string
      tipo:
        type: string

  Message:
    type: object
    properties:
      code:
        type: integer
        format: int32
      mensagem:
        type: string