swagger: "2.0"
info:
  description: "Aplicação de consulta star wars"
  version: "1.0.0"
  title: "star wars"
schemes:
- "https"
- "http"
paths:
    get:
      tags:
      summary:
      description:
      produces:
      responses:



definitions:
  
  PeopleResult:
    type: object
    properties:
      count:
        description: The name of this person.
        type: integer
        format: int32
      next:
        format: uri
        description: The url of this resource
        type: string
      previous:
        format: uri
        description: The url of this resource
        type: string 
      results:
        type: array
        items:
          $ref: "#/definitions/People"

  People: 
    type: object
    description: A person within the Star Wars universe
    required:
    - name
    - height
    - mass
    - hair_color
    - skin_color
    - eye_color
    - birth_year
    - gender
    - homeworld
    - films
    - species
    - vehicles
    - starships
    - url
    - created
    - edited
    properties:
      created:
        format: date-time
        description: The ISO 8601 date format of the time that this resource was created.
        type: string
      name:
        description: The name of this person.
        type: string
      edited:
        format: date-time
        description: the ISO 8601 date format of the time that this resource was edited.
        type: string
      starships:
        description: An array of starship resources that this person has piloted
        type: array
        items:
          type: string
      height:
        description: The height of this person in meters.
        type: string
      hair_color:
        description: The hair color of this person.
        type: string
      skin_color:
        description: The skin color of this person.
        type: string
      vehicles:
        description: An array of vehicle resources that this person has piloted
        type: array
        items:
          type: string
      gender:
        description: The gender of this person (if known).
        type: string
      url:
        format: uri
        description: The url of this resource
        type: string
      mass:
        description: The mass of this person in kilograms.
        type: string
      eye_color:
        description: The eye color of this person.
        type: string
      birth_year:
        description: The birth year of this person. BBY (Before the Battle of Yavin) or
          ABY (After the Battle of Yavin).
        type: string
      homeworld:
        description: The url of the planet resource that this person was born on.
        type: string
      species:
        description: The url of the species resource that this person is.
        type: array
        items:
          type: string
      films:
        description: An array of urls of film resources that this person has been in.
        type: array
        items:
          type: string
